import http from 'k6/http';
import { check, sleep } from 'k6';
import { SharedArray } from 'k6/data';

// Load the test data generated by our Node setup script
const testData = new SharedArray('testData', function () {
  return [JSON.parse(open('./k6_data.json'))];
});

export const options = {
    // Stage 1: Spike to 100 concurrent users immediately
    scenarios: {
        race_condition: {
            executor: 'per-vu-iterations',
            vus: 100, // 100 concurrent virtual users
            iterations: 1, // Each user places exactly 1 bid at the same time
            maxDuration: '10s',
        }
    },
    thresholds: {
        http_req_duration: ['p(95)<500'], // 95% of requests should complete within 500ms
        http_req_failed: ['rate>0.98'], // We EXPECT 99 out of 100 requests to fail (HTTP 400 Bad Request) due to DB locks! 
    },
};

// This function runs concurrently for every VU (Virtual User)
export default function () {
    const data = testData[0];
    const auctionId = data.auctionId;
    
    // Each VU gets a unique token based on their VU ID (1-100)
    // Arrays are 0-indexed, vu IDs start at 1
    const userIndex = (__VU - 1) % data.users.length;
    const token = data.users[userIndex].token;

    const url = `http://localhost:5001/api/auctions/${auctionId}/bid`;
    const payload = JSON.stringify({
        amount: 11.00, // Every user tries to be the winning $11.00 bidder
        idempotency_key: `${__VU}-${Date.now()}` // Unique tracing key per user
    });

    const params = {
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
        },
    };

    // The magical parallel GET request
    const res = http.post(url, payload, params);

    // K6 verifies the metrics over all requests
    check(res, {
        'is accepted (200) OR cleanly rejected (400)': (r) => {
            if (r.status !== 200 && r.status !== 400) {
                console.log(`[VU ${__VU}] Unexpected status ${r.status}: ${r.body}`);
                return false;
            }
            return true;
        },
        'if rejected, reason was BID_REJECTED': (r) => {
            if (r.status === 400) {
               const body = r.json();
               return body && body.error && body.error.code === 'BID_REJECTED';
            }
            return true;
        }
    });
}
